name: ubuntu

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [2.5]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Node.js setup
      uses: actions/setup-node@v2
      with:
        ruby-version: [2.5]
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
        npm ci
    - name: Run test
      run: rake test