name: livelelo_ci

on: [push]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ 2.7, 2.6, 2.5, 2.4, head ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Project Checkout
      uses: actions/checkout@v2
    - name: Node.js setup
      uses: actions/setup-node@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v2
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
        npm ci
    - name: Run test
      run: rake test