name: livelelo_ci

on: [push]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ 2.5, 2.4, head ]
        os: [ ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
     - name: Node.js setup
        uses: actions/setup-node@v2
      - name: Instalations for dependencies
        run: npm ci
    - name: Run test
      run: bundle exec cucumber